# Your Solution

version: '3'

services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://week7_e8nn_user:47k0v00mcGhZ4jFppCUdxpbkCtVokYGN@dpg-crr4b9dds78s73cqegtg-a.oregon-postgres.render.com/week7_e8nn

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://week7_e8nn_user:47k0v00mcGhZ4jFppCUdxpbkCtVokYGN@dpg-crr4b9dds78s73cqegtg-a.oregon-postgres.render.com/week7_e8nn